/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import house from './untitled.gltf'

export default function House({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(house)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} scale={5} rotation={[0,-Math.PI / 2,0]}/>
    </group>
  )
}

useGLTF.preload(house)
