/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import rig3 from './rig3.gltf';
import { useGLTF } from '@react-three/drei'
// import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {



  const group = useRef()
  const { nodes, materials } = useGLTF(rig3)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[1, 5, 1]} rotation={[0,Math.PI / 2,0]} >
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.004']}/>
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.005']}/>
      </group>
    </group>
  )
}

useGLTF.preload(rig3)
